language: java
jdk:
- oraclejdk8

before_install:
- mvn clean compile

# use latest java version available instead of travis default
addons:
  apt:
    packages:
    - oracle-java8-installer

sudo: required