language: java
jdk:
- oraclejdk8

before-install:
- mvn clean compile -Dmaven.javadoc.skip=true -B -V -e

install: true

# use latest java version available instead of travis default
addons:
  apt:
    packages:
    - oracle-java8-installer

sudo: required
